[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"

[[edge_functions]]
  path = "/*"
  excludedPath = ["/.netlify/*", "/assets/*", "/api/*"]
  function = "auth"
